<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        DB::table('vehicles')->insert([
            [
                'plat' => 'AB 41 CE',
                'pengguna' => 'Edy winarya, S.Sn',
                'jenis_kendaraan' => 'Rush, mini bus',
                'waktu_pajak' => 'Januari',
                'ganti_plat' => '2021',
                'usia_kendaraan' => '5 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456789',
            ],
            [
                'plat' => 'AB 1312 CE',
                'pengguna' => 'Anas Mubakkir, SS',
                'jenis_kendaraan' => 'Avansa, mini bus',
                'waktu_pajak' => 'Februari',
                'ganti_plat' => '2024',
                'usia_kendaraan' => '10 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456780',
            ],
            [
                'plat' => 'AB 1044 ZX',
                'pengguna' => 'Arif Marwoto, S.H., MAP',
                'jenis_kendaraan' => 'Rush, mini bus',
                'waktu_pajak' => 'April',
                'ganti_plat' => '2024',
                'usia_kendaraan' => '7 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456781',
            ],
            [
                'plat' => 'AB 1236 CE',
                'pengguna' => 'Ignatius Eko Ferianto, S.Sn., M.E',
                'jenis_kendaraan' => 'Avansa, mini bus',
                'waktu_pajak' => 'Mei',
                'ganti_plat' => '2024',
                'usia_kendaraan' => '6 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456782',
            ],
            [
                'plat' => 'AB 1116 CE',
                'pengguna' => 'Esti Listyowati, SE, MM',
                'jenis_kendaraan' => 'Avansa, mini bus',
                'waktu_pajak' => 'Juni',
                'ganti_plat' => '2021',
                'usia_kendaraan' => '4 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456783',
            ],
            [
                'plat' => 'AB 2652 ZX',
                'pengguna' => 'Ari Triyono, S.T., M.Si',
                'jenis_kendaraan' => 'VARIO',
                'waktu_pajak' => 'Juli',
                'ganti_plat' => '2025',
                'usia_kendaraan' => '0 th',
                'cc' => 125,
                'nomor_telepon' => '08123456784',
            ],
            [
                'plat' => 'AB 2659 ZX',
                'pengguna' => 'Wiwiek Diani Wijayanti, S.Sn',
                'jenis_kendaraan' => 'VARIO',
                'waktu_pajak' => 'Juli',
                'ganti_plat' => '2025',
                'usia_kendaraan' => '0 th',
                'cc' => 125,
                'nomor_telepon' => '08123456785',
            ],
            [
                'plat' => 'AB 2687 ZX',
                'pengguna' => 'Y. Jasminto',
                'jenis_kendaraan' => 'VARIO',
                'waktu_pajak' => 'Juli',
                'ganti_plat' => '2025',
                'usia_kendaraan' => '0 th',
                'cc' => 125,
                'nomor_telepon' => '08123456786',
            ],
            [
                'plat' => 'AB 2800 DE',
                'pengguna' => 'Imam Muslikh Mahmudi, SIP',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'Agustus',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '7 th',
                'cc' => 125,
                'nomor_telepon' => '08123456787',
            ],
            [
                'plat' => 'AB 2038 CE',
                'pengguna' => 'Rini Setyawati, A.Md',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'September',
                'ganti_plat' => '2022',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456788',
            ],
            [
                'plat' => 'AB 2039 CE',
                'pengguna' => 'Arief Bowo Laksono, S.Sn.',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'September',
                'ganti_plat' => '2022',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456789',
            ],
            [
                'plat' => 'AB 2041 CE',
                'pengguna' => 'Ita Kurniawati, S.IP., MPA',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'September',
                'ganti_plat' => '2022',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456790',
            ],
            [
                'plat' => 'AB 8063 CE',
                'pengguna' => 'Sekretariat Dinas',
                'jenis_kendaraan' => 'Grandmax, Open',
                'waktu_pajak' => 'November',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '2 th',
                'cc' => 1500,
                'nomor_telepon' => '08123456791',
            ],
            [
                'plat' => 'AB 8006 CE',
                'pengguna' => 'UPTD MGM',
                'jenis_kendaraan' => 'Hilux, Open',
                'waktu_pajak' => 'November',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '7 th',
                'cc' => 2000,
                'nomor_telepon' => '08123456792',
            ],
            [
                'plat' => 'AB 2091 CE',
                'pengguna' => 'Endah Kusuma Wardani, S.Ant',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'November',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456793',
            ],
            [
                'plat' => 'AB 2060 DE',
                'pengguna' => 'Murtijo Budiyanto, S.Pd',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'November',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456794',
            ],
            [
                'plat' => 'AB 2371 CE',
                'pengguna' => 'Dekhi Nugroho, S.E., M.Ec. Dev.',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'Desember',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456795',
            ],
            [
                'plat' => 'AB 2382 CE',
                'pengguna' => 'Suparyati, S.Ant',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'Desember',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456796',
            ],
            [
                'plat' => 'AB 2372 CE',
                'pengguna' => 'Mei Hartini, SS',
                'jenis_kendaraan' => 'motor',
                'waktu_pajak' => 'Desember',
                'ganti_plat' => '2023',
                'usia_kendaraan' => '10 th',
                'cc' => 100,
                'nomor_telepon' => '08123456797',
            ],
        ]);
    }
}
