<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        DB::table('vehicles')->insert([
            [
                'kode_kendaraan' => 'mbl-1',
                'plat' => 'AB 41 CE',
                'pengguna' => 'Edy winarya, S.Sn',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-10-24',
                'ganti_plat' => '2021',
                'usia_kendaraan' => 5,
                'cc' => 1500,
                'nomor_telepon' => '085869278611',
            ],
            [
                'kode_kendaraan' => 'mbl-2',
                'plat' => 'AB 1312 CE',
                'pengguna' => 'Anas Mubakkir, SS',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-02-01',
                'ganti_plat' => '2024',
                'usia_kendaraan' => 10,
                'cc' => 1500,
                'nomor_telepon' => '08123456780',
            ],
            [
                'kode_kendaraan' => 'mbl-3',
                'plat' => 'AB 1044 ZX',
                'pengguna' => 'Arif Marwoto, S.H., MAP',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-04-01',
                'ganti_plat' => '2024',
                'usia_kendaraan' => 7,
                'cc' => 1500,
                'nomor_telepon' => '08123456781',
            ],
            [
                'kode_kendaraan' => 'mbl-4',
                'plat' => 'AB 1236 CE',
                'pengguna' => 'Ignatius Eko Ferianto, S.Sn., M.E',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-05-01',
                'ganti_plat' => '2024',
                'usia_kendaraan' => 6,
                'cc' => 1500,
                'nomor_telepon' => '08123456782',
            ],
            [
                'kode_kendaraan' => 'mbl-5',
                'plat' => 'AB 1116 CE',
                'pengguna' => 'Esti Listyowati, SE, MM',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-06-01',
                'ganti_plat' => '2021',
                'usia_kendaraan' => 4,
                'cc' => 1500,
                'nomor_telepon' => '08123456783',
            ],
            [
                'kode_kendaraan' => 'mtr-1',
                'plat' => 'AB 2652 ZX',
                'pengguna' => 'Ari Triyono, S.T., M.Si',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-07-01',
                'ganti_plat' => '2025',
                'usia_kendaraan' => 0,
                'cc' => 125,
                'nomor_telepon' => '08123456784',
            ],
            [
                'kode_kendaraan' => 'mtr-2',
                'plat' => 'AB 2659 ZX',
                'pengguna' => 'Wiwiek Diani Wijayanti, S.Sn',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-07-01',
                'ganti_plat' => '2025',
                'usia_kendaraan' => 0,
                'cc' => 125,
                'nomor_telepon' => '08123456785',
            ],
            [
                'kode_kendaraan' => 'mtr-3',
                'plat' => 'AB 2687 ZX',
                'pengguna' => 'Y. Jasminto',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-07-01',
                'ganti_plat' => '2025',
                'usia_kendaraan' => 0,
                'cc' => 125,
                'nomor_telepon' => '08123456786',
            ],
            [
                'kode_kendaraan' => 'mtr-4',
                'plat' => 'AB 2800 DE',
                'pengguna' => 'Imam Muslikh Mahmudi, SIP',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-08-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 7,
                'cc' => 125,
                'nomor_telepon' => '08123456787',
            ],
            [
                'kode_kendaraan' => 'mtr-5',
                'plat' => 'AB 2038 CE',
                'pengguna' => 'Rini Setyawati, A.Md',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-09-01',
                'ganti_plat' => '2022',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456788',
            ],
            [
                'kode_kendaraan' => 'mtr-6',
                'plat' => 'AB 2039 CE',
                'pengguna' => 'Arief Bowo Laksono, S.Sn.',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-09-01',
                'ganti_plat' => '2022',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456789',
            ],
            [
                'kode_kendaraan' => 'mtr-7',
                'plat' => 'AB 2041 CE',
                'pengguna' => 'Ita Kurniawati, S.IP., MPA',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-09-01',
                'ganti_plat' => '2022',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456790',
            ],
            [
                'kode_kendaraan' => 'mbl-6',
                'plat' => 'AB 8063 CE',
                'pengguna' => 'Sekretariat Dinas',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-11-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 2,
                'cc' => 1500,
                'nomor_telepon' => '08123456791',
            ],
            [
                'kode_kendaraan' => 'mbl-7',
                'plat' => 'AB 8006 CE',
                'pengguna' => 'UPTD MGM',
                'jenis_kendaraan' => 'Mobil',
                'waktu_pajak' => '2024-11-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 7,
                'cc' => 2000,
                'nomor_telepon' => '08123456792',
            ],
            [
                'kode_kendaraan' => 'mtr-8',
                'plat' => 'AB 2091 CE',
                'pengguna' => 'Endah Kusuma Wardani, S.Ant',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-11-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456793',
            ],
            [

                'kode_kendaraan' => 'mtr-9',
                'plat' => 'AB 2060 DE',
                'pengguna' => 'Murtijo Budiyanto, S.Pd',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-11-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456794',
            ],
            [
                'kode_kendaraan' => 'mtr-10',
                'plat' => 'AB 2371 CE',
                'pengguna' => 'Dekhi Nugroho, S.E., M.Ec. Dev.',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-12-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456795',
            ],
            [
                'kode_kendaraan' => 'mtr-11',
                'plat' => 'AB 2382 CE',
                'pengguna' => 'Suparyati, S.Ant',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-12-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456796',
            ],
            [
                'kode_kendaraan' => 'mtr-12',
                'plat' => 'AB 2372 CE',
                'pengguna' => 'Mei Hartini, SS',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-12-01',
                'ganti_plat' => '2023',
                'usia_kendaraan' => 10,
                'cc' => 100,
                'nomor_telepon' => '08123456797',
            ],
            [
                'kode_kendaraan' => 'mtr-13',
                'plat' => 'AB 1111 CE',
                'pengguna' => 'Jihan Cindaga S.Kom',
                'jenis_kendaraan' => 'Motor',
                'waktu_pajak' => '2024-12-01',
                'ganti_plat' => '2024',
                'usia_kendaraan' => 5,
                'cc' => 150,
                'nomor_telepon' => '085869278611',
            ],
        ]);
    }
}
